- name: Deploy Microservices
  hosts: localhost
  vars_files:
    - ../vars/config.yml
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ k8s_namespace }}"

    - name: Deploy service1
      kubernetes.core.k8s:
        state: present
        definition: "{{ service1_manifest | from_yaml }}" 
    
    - name: Deploy service2
      kubernetes.core.k8s:
        state: present
        definition: "{{ service2_manifest | from_yaml }}"

